const patterns = {
    'ukStore': {
        date: 'date/time',
        type: 'type',
        sku: 'sku',
        quantity: 'quantity',
        marketplace: 'marketplace',
        product_sales: 'product sales',
        total: 'total',
    },
    'usStore': {
        date: 'date/time',
        type: 'type',
        sku: 'sku',
        quantity: 'quantity',
        marketplace: 'marketplace',
        product_sales: 'product sales',
        total: 'total',
    },
    'caStore': {
        date: 'date/time',
        type: 'type',
        sku: 'sku',
        quantity: 'quantity',
        marketplace: 'marketplace',
        product_sales: 'product sales',
        total: 'total',
    },
    'esStore': {
        date: 'fecha y hora',
        type: 'tipo',
        sku: 'sku',
        quantity: 'cantidad',
        marketplace: 'web de Amazon',
        product_sales: 'ventas de productos',
        total: 'total',
    },
    'poStore': {
        date: 'data/godzina',
        type: 'typ',
        sku: 'sku',
        quantity: 'ilość',
        marketplace: 'rynek',
        product_sales: 'noty kredytowe za wysyłkę',
        total: 'suma',
    },
    'frStore': {
        date: 'date/heure',
        type: 'type',
        sku: 'sku',
        quantity: 'quantité',
        marketplace: 'Marketplace',
        product_sales: 'ventes de produits',
        total: 'total',
    },
    'geStore': {
        date: 'Datum/Uhrzeit',
        type: 'Typ',
        sku: 'SKU',
        quantity: 'Menge',
        marketplace: 'Marketplace',
        product_sales: 'Umsätze',
        total: 'Gesamt',
    },
    'mxStore': {
        date: 'fecha/hora',
        type: 'tipo',
        sku: 'sku',
        quantity: 'cantidad',
        marketplace: 'marketplace',
        product_sales: 'ventas de productos',
        total: 'total',
    },
    'nlStore': {
        date: 'datum/tijd',
        type: 'type',
        sku: 'sku',
        quantity: 'aantal',
        marketplace: 'marketplace',
        product_sales: 'Verzendtegoeden',
        total: 'totaal',
    },
    'swStore': {
        date: 'datum/tid',
        type: 'typ',
        sku: 'sku',
        quantity: 'antal',
        marketplace: 'marknadsplats',
        product_sales: 'Produktförsäljning',
        total: 'total',
    }
}

module.exports = { patterns }